(()=>{
'use strict';
const $=id=>document.getElementById(id);const money=n=>'$'+new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cars=[],limit=9,body='';const fields=['search','make','model','price-min','price-max','year-min','year-max','fuel','mileage','seats'];
function models(){const select=$('model'),value=select.value,brand=$('make').value,values=window.JHTVehicleOptions.models(cars,brand);select.disabled=!brand||!values.length;select.innerHTML='<option value="">'+(!brand?'Choose a brand first':!values.length?'No models in stock':'All models')+'</option>'+values.map(m=>'<option>'+esc(m)+'</option>').join('');if(values.includes(value))select.value=value;}
function validRange(){let error='';if($('price-min').value&&$('price-max').value&&+$('price-min').value>+$('price-max').value)error='The minimum price must be lower than the maximum price.';if($('year-min').value&&$('year-max').value&&+$('year-min').value>+$('year-max').value)error='The starting year must be earlier than the ending year.';if(+$('price-min').value<0||+$('price-max').value<0)error='Please enter a price of zero or more.';$('range-error').textContent=error;$('range-error').hidden=!error;return !error;}
function filtered(){const q=$('search').value.toLowerCase().trim();return cars.filter(c=>(!q||`${c.brand} ${c.model} ${c.year} ${c.ref}`.toLowerCase().includes(q))&&(!body||c.body===body)&&(!$('make').value||c.brand===$('make').value)&&(!$('model').value||c.model===$('model').value)&&(!$('price-min').value||c.price>=+$('price-min').value)&&(!$('price-max').value||c.price<=+$('price-max').value)&&(!$('year-min').value||c.year>=+$('year-min').value)&&(!$('year-max').value||c.year<=+$('year-max').value)&&(!$('fuel').value||c.fuel===$('fuel').value)&&(!$('mileage').value||(c.mileage!==null&&c.mileage<=+$('mileage').value))&&(!$('seats').value||($('seats').value==='7'?c.seats>=7:c.seats===5)));}
function card(c,i){return `<article class="car-card" style="--i:${i%9}"><a class="car-photo" href="/jhtkorea/cars/${c.slug}/" aria-label="View ${c.year} ${esc(c.brand)} ${esc(c.model)}"><img src="/jhtkorea/${c.image}" alt="${c.year} ${esc(c.brand)} ${esc(c.model)}" width="800" height="563" loading="lazy"><span class="car-type">${c.status==='reserved'?'RESERVED':esc(c.body.toUpperCase())}</span></a><div class="car-info"><p class="car-meta">${esc(c.brand)} / ${c.year}</p><h3><a href="/jhtkorea/cars/${c.slug}/">${esc(c.model)}</a></h3><p class="car-specs"><span>${esc(c.fuel)}</span><span>${esc(c.transmission)}</span><span>${c.seats} seats</span></p><div class="car-bottom"><p class="car-price">${money(c.price)}<small>USD</small></p><a class="view-car" href="/jhtkorea/cars/${c.slug}/">View car <span>↗</span></a></div></div></article>`}
function chips(){const labels={search:'Search',make:'Make',model:'Model','price-min':'Min price','price-max':'Max price','year-min':'From','year-max':'To',fuel:'Fuel',mileage:'Max km',seats:'Seats'};let active=fields.filter(id=>$(id).value).map(id=>({id,label:labels[id]+': '+(id.startsWith('price')?money(+$(id).value):$(id).value)}));if(body)active.unshift({id:'body',label:body});$('active-filters').innerHTML=active.map(a=>`<button class="filter-chip" data-clear="${a.id}" aria-label="Remove ${esc(a.label)}">${esc(a.label)} <span aria-hidden="true">×</span></button>`).join('');$('filter-count').textContent=active.length||''}
function updateURL(){const params=new URLSearchParams();for(const id of fields)if($(id).value)params.set(id,$(id).value);if(body)params.set('body',body);if($('sort').value!=='featured')params.set('sort',$('sort').value);history.replaceState(null,'',location.pathname+(params.size?'?'+params:''))}
function render(write=true,animate=false){let list=validRange()?filtered():[];const sort=$('sort').value;list.sort(sort==='price-up'?(a,b)=>a.price-b.price:sort==='price-down'?(a,b)=>b.price-a.price:sort==='year'?(a,b)=>b.year-a.year:sort==='mileage'?(a,b)=>(a.mileage??Infinity)-(b.mileage??Infinity):(a,b)=>b.createdAt-a.createdAt);$('car-grid').innerHTML=list.slice(0,limit).map(card).join('');$('results-count').innerHTML=`<b>${list.length} ${list.length===1?'car':'cars'}</b> to explore`;$('empty').hidden=list.length>0;const requested=$('make').value;const unavailable=requested&&!cars.some(c=>c.brand===requested);$('empty-text').textContent=unavailable?`There are no ${requested} cars in the current collection. Tell us what you need and we can search for it.`:'No cars match this combination. Try widening your search.';$('empty-source').href='https://wa.me/821036563439?text='+encodeURIComponent(`Hello JHT Korea, I am looking for a ${requested||'car'} from Korea.`);$('load-more').hidden=list.length<=limit;$('showing-count').textContent=list.length?`Showing ${Math.min(limit,list.length)} of ${list.length} cars`:'';$('all-count').textContent=cars.length;$('apply-mobile').textContent=`Show ${list.length} matching ${list.length===1?'car':'cars'} ↗`;document.querySelectorAll('[data-body]').forEach(b=>{b.classList.toggle('active',b.dataset.body===body);b.setAttribute('aria-pressed',String(b.dataset.body===body))});chips();if(write)updateURL();if(animate)window.JHTUI?.enter($('car-grid'),{duration:180,distance:4})}
function reset(){fields.forEach(id=>$(id).value='');body='';limit=9;$('sort').value='featured';models();render(true,true)}
let filterTrigger=null;
function drawer(open){if(open)filterTrigger=document.activeElement;$('filters').classList.toggle('open',open);document.body.classList.toggle('filters-open',open);window.jhtScrollLock?.(open,'filters');if(open){window.JHTUI?.enter($('filters'),{duration:220,distance:0});$('filters').setAttribute('role','dialog');$('filters').setAttribute('aria-modal','true');$('close-filters').focus()}else{$('filters').removeAttribute('role');$('filters').removeAttribute('aria-modal');filterTrigger?.focus({preventScroll:true})}}
fields.forEach(id=>$(id).addEventListener(id==='search'||id.startsWith('price')?'input':'change',()=>{if(id==='make'){$('model').value='';models()}limit=9;render(true,!['search','price-min','price-max'].includes(id))}));$('sort').onchange=()=>render(true,true);$('reset').onclick=reset;$('empty-reset').onclick=reset;$('load-more').onclick=()=>{limit+=9;render(true,true)};document.querySelectorAll('[data-body]').forEach(b=>b.onclick=()=>{body=b.dataset.body;limit=9;render(true,true)});$('active-filters').onclick=e=>{const chip=e.target.closest('[data-clear]');if(!chip)return;const id=chip.dataset.clear;if(id==='body')body='';else{$(id).value='';if(id==='make'){$('model').value='';models()}}limit=9;render()};$('open-filters').onclick=()=>drawer(true);$('close-filters').onclick=()=>drawer(false);$('apply-mobile').onclick=()=>drawer(false);document.addEventListener('keydown',e=>{if(!$('filters').classList.contains('open'))return;if(e.key==='Escape')drawer(false);if(e.key==='Tab'){const controls=[...$('filters').querySelectorAll('button,input,select,a')].filter(x=>x.offsetParent!==null),first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});addEventListener('resize',()=>{if(innerWidth>800&&$('filters').classList.contains('open'))drawer(false)});
async function init(){try{const r=await fetch('/jhtkorea/cars.json',{cache:'no-store'});if(!r.ok)throw Error('Collection unavailable');const payload=await r.json();cars=window.JHTSecurity.vehicles(Array.isArray(payload)?payload:payload.vehicles);const selectedMake=new URLSearchParams(location.search).get('make');const brands=window.JHTVehicleOptions.brands([...cars,...(selectedMake&&selectedMake.length<=120?[{brand:selectedMake}]:[])]);$('make').innerHTML='<option value="">All brands</option>'+brands.map(brand=>`<option>${esc(brand)}</option>`).join('');for(const id of ['year-min','year-max'])for(let y=2026;y>=2010;y--){const o=document.createElement('option');o.value=y;o.textContent=y;$(id).append(o)}const p=new URLSearchParams(location.search);for(const id of fields)if(id!=='model'&&p.has(id))$(id).value=p.get(id);models();if(p.has('model'))$('model').value=p.get('model');if(['SUV','Sedan','Hatchback','Van'].includes(p.get('body')))body=p.get('body');if(p.has('sort'))$('sort').value=p.get('sort');render(false,true)}catch(e){$('car-grid').innerHTML='';$('results-count').textContent='Collection unavailable';$('empty').hidden=false;$('empty').querySelector('h3').textContent='Let’s try that again.';$('empty-text').textContent='The collection could not load. Please refresh the page or contact our team.';$('empty-reset').textContent='Reload collection';$('empty-reset').onclick=()=>location.reload()}}init();


})();
