const test=require('node:test');
const assert=require('node:assert/strict');
const {mkdtemp,mkdir,writeFile,readFile,copyFile,readdir}=require('node:fs/promises');
const {join}=require('node:path');
const {tmpdir}=require('node:os');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const {createHash}=require('node:crypto');

test('production build isolates secrets, keeps Pages closed and supplies the real same-origin sign-in only on Netlify',async()=>{
  const root=await mkdtemp(join(tmpdir(),'jht-build-security-'));
  for(const dir of ['security','public-site/admin','public-site/.github','private-ui/admin','private-ui/bidding','backend','public-site/cars/hidden-car'])await mkdir(join(root,dir),{recursive:true});
  await writeFile(join(root,'private-ui/bidding/index.html'),'PRIVATE_BIDDING_UI');
  for(const file of ['auction-utils.js','auction-ui.css'])await writeFile(join(root,'private-ui',file),'BIDDING_SHARED');
  const boot="window.theme='dark';";
  await writeFile(join(root,'public-site/index.html'),`<head><script>${boot}</script></head><a href="/jhtkorea/cars/">Cars</a><div id="latest-carousel"><article class="car-card"><div>STALE_INVENTORY_CANARY</div></article></div><section id="about">Story stays</section><footer>Footer stays</footer>`);
  await writeFile(join(root,'public-site/cars/hidden-car/index.html'),'STALE_DETAIL_CANARY');
  await writeFile(join(root,'public-site/cars.json'),'STALE_INVENTORY_CANARY');
  await writeFile(join(root,'public-site/catalogue.js'),"fetch('/jhtkorea/cars.json',{cache:'no-store'});");
  await writeFile(join(root,'private-ui/live-home.js'),'LIVE_COLLECTION_LOADER');
  await writeFile(join(root,'private-ui/live-content.css'),'FEATURE_SECTION_STYLE');
  await writeFile(join(root,'private-ui/admin-shortcut.js'),'SESSION_GATED_SHORTCUT');
  await writeFile(join(root,'public-site/admin/index.html'),'Management access is closed.');
  await writeFile(join(root,'public-site/.github/workflow.yml'),'PRIVATE_WORKFLOW');
  await writeFile(join(root,'backend/private.mjs'),'SECRET_CANARY');
  await writeFile(join(root,'.env'),'SECRET_CANARY');
  await writeFile(join(root,'private-ui/admin/index.html'),'<script src="/admin/access.js"></script>Private sign-in');
  await writeFile(join(root,'private-ui/admin/access.js'),"fetch('/api/auth/session');");
  await copyFile(join(__dirname,'build-netlify.mjs'),join(root,'security/build-netlify.mjs'));
  await promisify(execFile)(process.execPath,[join(root,'security/build-netlify.mjs')]);
  const output=join(root,'netlify-public');
  assert.match(await readFile(join(output,'index.html'),'utf8'),/id="featured-vehicle-section"/);
  assert.match(await readFile(join(output,'index.html'),'utf8'),/Story stays/);
  const entries=await readdir(output);
  for(const forbidden of ['backend','.env','.github','private-ui','security'])assert.equal(entries.includes(forbidden),false);
  assert.match(await readFile(join(output,'index.html'),'utf8'),/href="\/cars\/"/);
  const home=await readFile(join(output,'index.html'),'utf8');assert.doesNotMatch(home,/STALE_INVENTORY_CANARY/);assert.match(home,/\/security-data.js/);assert.match(home,/Footer stays/);
  assert.equal(entries.includes('cars.json'),false);assert.deepEqual(await readdir(join(output,'cars')),[]);
  assert.match(await readFile(join(output,'catalogue.js'),'utf8'),/\/api\/public\/catalogue/);
  assert.match(await readFile(join(output,'admin/index.html'),'utf8'),/Private sign-in/);
  assert.match(await readFile(join(root,'public-site/admin/index.html'),'utf8'),/access is closed/);
  const headers=await readFile(join(output,'_headers'),'utf8');
  assert.ok(headers.includes(createHash('sha256').update(boot).digest('base64')));
  assert.match(await readFile(join(output,'bidding/index.html'),'utf8'),/PRIVATE_BIDDING_UI/);
  assert.match(headers,/\/bidding\/\*/);
  assert.match(headers,/frame-ancestors 'none'/);
  assert.doesNotMatch(headers,/unsafe-eval|script-src[^;]*unsafe-inline/);
});
