(() => {
 'use strict';
 const U=window.JHTAuction,$=s=>document.querySelector(s);
 let ctx,connection=null,data=null,events=[],filter='all',lastFresh=0,startRoom=null,lastOptions='',lastCards='',lastFeed='',lastPhases='';
 const phases=()=>data.lots.map(l=>U.now()<Date.parse(l.starts_at)?'upcoming':U.now()<Date.parse(l.closes_at)?'live':'closed').join(',');
 const kinds={bid:'Bid placed',start:'Bidding opened',notice:'Start notice posted',close:'Car closed early',confirm:'Winner confirmed',cancel:'Session cancelled'};
 function render(){
  if(!data)return;lastPhases=phases();const session=$('#live-session-filter'),chosen=session.value;
  const names=[...new Map(data.lots.map(l=>[l.session_slug,l.session_title])).entries()],options='<option value="">All sessions</option>'+names.map(([slug,title])=>`<option value="${U.escape(slug)}">${U.escape(title)}</option>`).join('');
  if(options!==lastOptions){session.innerHTML=options;session.value=chosen;lastOptions=options;}
  const selected=data.lots.filter(l=>!session.value||l.session_slug===session.value),live=l=>U.now()>=Date.parse(l.starts_at)&&U.now()<Date.parse(l.closes_at);
  $('#live-count').textContent=selected.filter(live).length;$('#live-pending').textContent=selected.filter(l=>U.now()>=Date.parse(l.closes_at)&&l.highest_amount&&!l.confirmed).length;$('#live-bids').textContent=selected.reduce((n,l)=>n+l.bid_count,0);
  const stale=performance.now()-lastFresh>15000;
  const cards=selected.filter(l=>filter==='all'||filter==='live'&&live(l)||filter==='pending'&&U.now()>=Date.parse(l.closes_at)&&!!l.highest_amount).map(l=>{
   const open=live(l),future=U.now()<Date.parse(l.starts_at),pending=!open&&!future&&!!l.highest_amount;
   return `<article class="live-car" data-live-car="${l.id}"><img src="${U.asset(l.vehicle.image)}" alt="${U.escape(l.vehicle.brand+' '+l.vehicle.model)}"><div class="live-car-copy"><p>${U.escape(l.session_title)} <span>${future?'Upcoming':open?'Live':l.confirmed?'Confirmed':'Awaiting confirmation'}</span></p><h2>${U.escape(l.vehicle.brand+' '+l.vehicle.model)}</h2><small>${U.escape(l.vehicle.ref)} · ${l.vehicle.year}</small><div class="live-car-price"><strong>${U.money(l.highest_amount||l.next_bid)}</strong><span>${l.highest_amount?'Highest bid':'Opening bid'}</span></div><dl><div><dt>Leading member</dt><dd>${U.escape(l.leader||'No bids yet')}</dd></div><div><dt>${future?'Opens in':open?'Closes in':'Result'}</dt><dd ${future||open?`data-live-time="${future?l.starts_at:l.closes_at}"`:''}>${future||open?'':l.closed_early?'Closed early':'Closed'}</dd></div></dl><div class="live-car-actions"><button class="text-action" data-open-from-live="${U.escape(l.session_slug)}">Open session</button>${open&&l.highest_amount?`<button class="secondary-action" data-close-lot="${l.id}" data-highest="${l.highest_amount}" data-car="${U.escape(l.vehicle.brand+' '+l.vehicle.model)}" ${stale?'disabled':''}>Close bidding</button>`:''}${pending&&!l.confirmed?`<button class="primary-action" data-confirm-lot="${l.id}" ${stale?'disabled':''}>Confirm winner</button>`:''}</div></div></article>`;
  }).join('')||(filter==='pending'?'<div class="auction-empty"><h2>No results waiting.</h2><p>Cars with a winning bid appear here when bidding closes. Confirmed results stay in their session history.</p></div>':filter==='live'?'<div class="auction-empty"><h2>No cars accepting bids.</h2><p>Upcoming cars will appear here at their opening time. Use All cars to review the schedule.</p></div>':'<div class="auction-empty"><h2>Your next session starts here.</h2><p>Open a prepared session from Bidding sessions. Active cars and results awaiting your confirmation will appear here.</p></div>');
  if(cards!==lastCards){$('#live-auction-cars').innerHTML=cards;lastCards=cards;}for(const el of document.querySelectorAll('[data-live-time]'))el.textContent=U.countdown(el.dataset.liveTime);
  document.querySelectorAll('#live-auction-cars [data-close-lot],#live-auction-cars [data-confirm-lot]').forEach(b=>b.disabled=stale||document.body.classList.contains('is-saving'));
  const visibleEvents=events.filter(e=>!session.value||e.session_slug===session.value),feed=visibleEvents.map(e=>`<li><span class="live-event-mark ${e.kind==='bid'?'is-bid':''}" aria-hidden="true"></span><div><strong>${U.escape(e.kind==='bid'?e.bidder||'Invited member':kinds[e.kind])}</strong><p>${U.escape(e.car||e.session_title)}${e.ref?' · '+U.escape(e.ref):''}</p><time datetime="${e.at}">${U.date(e.at)}</time></div>${e.amount?`<b>${U.money(e.amount)}</b>`:''}</li>`).join('')||'<li class="live-feed-empty">Accepted bids and session controls will appear here.</li>';
  if(feed!==lastFeed){const panel=$('#live-bid-feed'),top=panel.scrollTop,height=panel.scrollHeight;panel.innerHTML=feed;if(top>20)panel.scrollTop=top+Math.max(0,panel.scrollHeight-height);lastFeed=feed;}
 }
 function receive(next){U.sync(next.server_now);data=next;lastFresh=performance.now();const all=new Map([...next.events,...events].map(e=>[e.seq,e]));events=[...all.values()].sort((a,b)=>BigInt(a.seq)>BigInt(b.seq)?-1:1).slice(0,200);$('#live-updated').textContent='Verified '+new Intl.DateTimeFormat(undefined,{timeStyle:'medium'}).format(new Date());$('#live-loading').hidden=true;render();}
 function connect(){connection?.close();lastFresh=-Infinity;$('#live-loading').hidden=!!data;render();connection=window.JHTLive.connect('/api/admin/auctions-live/stream',{onData:receive,onState:status=>{const label=$('#live-connection');label.textContent=status==='connected'?'Live connection':status==='paused'?'Updates paused in background':status==='connecting'?'Connecting…':'Reconnecting…';label.dataset.state=status;if(status==='interrupted')lastFresh=-Infinity;},onDenied:()=>location.replace('/admin/')});}
 async function openStart(slug){startRoom=await ctx.api('admin/auctions/'+encodeURIComponent(slug));U.sync(startRoom.server_now);$('#start-auction-form').reset();$('#start-auction-name').textContent=startRoom.session.title;$('#start-auction-duration').textContent=Math.round((Date.parse(startRoom.session.ends_at)-Date.parse(startRoom.session.starts_at))/60000)+' minutes of bidding · '+startRoom.lots.length+' cars';$('#start-auction-error').textContent='';noticeFields();$('#start-auction-editor').showModal();}
 function noticeFields(){const notice=$('#start-auction-mode').value==='notice';$('#start-notice-fields').hidden=!notice;$('#start-notice-text').required=notice;$('#start-auction-submit').textContent=notice?'Post notice & set opening':'Open bidding now';}
 function init(context){ctx=context;
  document.addEventListener('jht:admin-idle',()=>{if(connection)render();});
  document.addEventListener('jht:admin-view',event=>{if(event.detail==='live')connect();else{connection?.close();connection=null;}});
  $('#live-session-filter').addEventListener('change',render);$('#live-refresh').addEventListener('click',connect);
  document.querySelectorAll('[data-live-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.liveFilter;document.querySelectorAll('[data-live-filter]').forEach(b=>b.setAttribute('aria-pressed',b===button));render();}));
  $('#start-auction-mode').addEventListener('change',noticeFields);$('#close-start-auction').addEventListener('click',()=>window.JHTUI.closeDialog($('#start-auction-editor')));$('#start-auction-editor').addEventListener('cancel',e=>{if(document.body.classList.contains('is-saving'))e.preventDefault();});
  $('#start-auction-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!startRoom||!form.reportValidity())return;const notice=form.elements.mode.value==='notice';ctx.operate(async()=>{try{await ctx.api('admin/auctions/'+startRoom.session.id+'/start',{version:startRoom.session.version,notice_minutes:notice?Number(form.elements.minutes.value):0,notice:notice?form.elements.notice.value:''},'POST');window.JHTUI.closeDialog($('#start-auction-editor'));await ctx.refresh();ctx.showToast(notice?'Opening notice posted to the invited members’ bidding area.':'Bidding is open. Invited members can bid now.');}catch(error){$('#start-auction-error').textContent=error.message;throw error;}},notice?'Posting the opening notice…':'Opening bidding…');});
  document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;
   if(button.dataset.startSession){button.disabled=true;try{await openStart(button.dataset.startSession);}catch(error){ctx.showToast(error.message,'error');}finally{button.disabled=false;}}
   if(button.dataset.openFromLive){try{await ctx.openSession(button.dataset.openFromLive);}catch(error){ctx.showToast(error.message,'error');}}
   if(button.dataset.closeLot){const amount=Number(button.dataset.highest),id=button.dataset.closeLot,name=button.dataset.car;
    if(await window.JHTUI.confirm({title:'Close bidding for '+name+'?',message:'Keep the highest bid of '+U.money(amount)+' for your confirmation. This car stops accepting bids immediately; the other cars continue.',label:'Close this car',cancelLabel:'Keep bidding'}))ctx.operate(async()=>{await ctx.api('admin/auctions/lots/'+id+'/close',{highest_amount:amount},'POST');await ctx.refresh();ctx.showToast('Bidding closed for this car. The highest bid is retained for confirmation.');},'Closing this car…');
   }
  });
  setInterval(()=>{if(!data||!connection||document.hidden)return;if(phases()!==lastPhases)render();for(const el of document.querySelectorAll('[data-live-time]'))el.textContent=U.countdown(el.dataset.liveTime);if(performance.now()-lastFresh>15000)document.querySelectorAll('#live-auction-cars [data-close-lot],#live-auction-cars [data-confirm-lot]').forEach(b=>b.disabled=true);},1000);
 }
 window.JHTAuctionDesk={init};
})();
