(() => {
 'use strict';
 const U=window.JHTAuction,$=s=>document.querySelector(s);
 let ctx,sessions=[],bidders=[],bidCars=[],editing=null,room=null,active='',loading=false,poll,saveSlug='',lastSessions='',lastMembers='';
 function localInput(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 function render(){
 $('#bid-car-list').innerHTML=bidCars.length?bidCars.map(v=>`<article class="bid-stock-card"><img src="${U.asset(v.image)}" alt="${U.escape(v.brand+' '+v.model)}"><div><span class="auction-eyebrow">${U.escape(v.ref)} · PRIVATE BIDDING</span><h2>${U.escape(v.brand+' '+v.model)}</h2><p>${v.year} · ${U.escape(v.fuel)} · ${v.mileage==null?'Mileage to confirm':Number(v.mileage).toLocaleString()+' km'}</p><strong>${U.money(v.price)} <small>Suggested opening bid</small></strong><p class="auction-badge">${U.escape(v.locked?'Assigned to bidding':v.status==='available'?'Ready for bidding':v.status)}</p><div class="auction-session-actions"><button class="secondary-action" data-edit-bid-car="${v.id}" ${v.locked?'disabled title="Cancel the assigned session before editing"':''}>Edit car & photos</button>${v.status!=='archived'?`<button class="text-action" data-archive-bid-car="${v.id}" ${v.locked?'disabled title="Cancel the assigned session before archiving"':''}>Archive</button>`:''}</div></div></article>`).join(''):'<div class="auction-empty"><h2>Your next bidding collection.</h2><p>Upload newly sourced cars here, then assign them to a private session. Sale cars stay in Inventory.</p></div>';

 const sessionMarkup=sessions.length?sessions.map(s=>`<article class="auction-session-card"><div><span class="auction-badge ${U.phase(s)}">${U.escape(U.phase(s))}</span><h2>${U.escape(s.title)}</h2><p>${U.date(s.starts_at)} — ${U.date(s.ends_at)}</p><small>${s.lot_count} car${s.lot_count===1?'':'s'} · ${s.bid_count} ${s.bid_count===1?'bid':'bids'}</small></div><div class="auction-session-actions"><button class="secondary-action" data-monitor="${U.escape(s.slug)}">Open session</button><button class="text-action" data-copy-session="${U.escape(s.slug)}">Copy private link</button>${['draft','scheduled'].includes(U.phase(s))?`<button class="text-action" data-edit-session="${U.escape(s.slug)}">Edit schedule</button>`:''}${s.status!=='cancelled'?`<button class="text-action" data-cancel-session="${s.id}">Cancel session</button>`:''}</div></article>`).join(''):'<div class="auction-empty"><span class="auction-eyebrow">YOUR FIRST PRIVATE EVENT</span><h2>A considered selection.<br>A room of invited buyers.</h2><p>Invite your members, select one or more cars, then choose when bidding opens.</p></div>';
 const memberMarkup=bidders.length?bidders.map(b=>`<article class="auction-member-row"><div class="auction-avatar">${U.escape(b.name.slice(0,1).toUpperCase())}</div><div><strong>${U.escape(b.name)}</strong><span>${U.escape(b.email)}</span></div><span class="auction-badge ${b.enabled?'scheduled':'cancelled'}">${!b.invite_delivered?'Invitation not sent':b.enabled?(b.activation_pending?'Setup pending':'Active'):'Disabled'}</span>${b.invite_delivered?`<button class="secondary-action" data-toggle-member="${b.id}" data-enabled="${!b.enabled}">${b.enabled?'Disable access':'Enable access'}</button>`:`<button class="secondary-action" data-retry-member="${b.id}">Retry invitation</button>`}</article>`).join(''):'<div class="auction-empty"><h2>Your guest list starts here.</h2><p>Invite a member by email. Their account never grants access to the admin dashboard.</p></div>';
 if(sessionMarkup!==lastSessions||$('#auction-session-list').querySelector('.auction-loading')){$('#auction-session-list').innerHTML=sessionMarkup;lastSessions=sessionMarkup;}if(memberMarkup!==lastMembers||$('#bidder-list').querySelector('.auction-loading')){$('#bidder-list').innerHTML=memberMarkup;lastMembers=memberMarkup;}
 }
 async function refresh(){if(loading)return;loading=true;$('#new-auction').disabled=true;try{const [list,members,stock]=await Promise.all([ctx.api('admin/auctions'),ctx.api('admin/bidders'),ctx.api('admin/bid-vehicles')]);U.sync(list.server_now);sessions=list.sessions;bidders=members.bidders;bidCars=stock.vehicles;render();if(room)await monitor(room.session.slug);}catch(error){lastSessions='';lastMembers='';$('#auction-session-list').innerHTML=`<div class="auction-empty"><h2>Bidding is unavailable.</h2><p>${U.escape(error.message)}</p><button type="button" class="secondary-action" id="retry-auctions">Try again</button></div>`;$('#bidder-list').innerHTML='<div class="auction-empty"><p>Member management becomes available when the bidding database is configured.</p></div>';}finally{loading=false;$('#new-auction').disabled=false;}}
 async function monitor(slug){room=await ctx.api('admin/auctions/'+encodeURIComponent(slug));U.sync(room.server_now);const r=room,s=r.session;
 const pane=$('#auction-monitor'),expanded=[...pane.querySelectorAll('[data-monitor-lot] details[open]')].map(d=>d.closest('[data-monitor-lot]').dataset.monitorLot);pane.hidden=false;pane.innerHTML=`<div class="auction-monitor-heading"><div><span class="auction-eyebrow">SESSION MONITOR</span><h2>${U.escape(s.title)}</h2><p>Refreshes while this screen is open. ${U.date(s.starts_at)}</p></div><a class="secondary-action" href="/bidding/?session=${encodeURIComponent(s.slug)}" target="_blank" rel="noopener">Open bidder sign-in</a></div><div class="auction-monitor-grid">${r.lots.map(l=>`<article data-monitor-lot="${l.id}"><img src="${U.asset(l.vehicle.image)}" alt="${U.escape(l.vehicle.brand+' '+l.vehicle.model)}"><h3>${U.escape(l.vehicle.brand+' '+l.vehicle.model)}</h3><div class="auction-monitor-price">${U.money(l.highest_amount||l.opening_amount)}<small>${l.highest_amount?'Highest bid':'Opening price'}</small></div><p>${l.bid_count} ${l.bid_count===1?'bid':'bids'} · closes ${U.date(l.closes_at)}</p><p>${l.leader?`Leading member: <strong>${U.escape(l.leader.name)}</strong><br>${U.escape(l.leader.email)}`:'No bids yet.'}</p>${s.status==='scheduled'&&U.now()>=Date.parse(l.closes_at)&&l.highest_amount?`<button class="primary-action" data-confirm-lot="${l.id}" ${l.confirmed?'disabled':''}>${l.confirmed?'Winner confirmed':'Confirm winner & reserve car'}</button>`:''}<details><summary>Bid history</summary><ol class="auction-history">${l.history.map(h=>`<li><span>${U.escape(h.name||'Member')}<small>${U.date(h.created_at)}</small></span><strong>${U.money(h.amount)}</strong></li>`).join('')||'<li>No bids yet.</li>'}</ol></details></article>`).join('')}</div>`;
 for(const id of expanded){const details=pane.querySelector(`[data-monitor-lot="${id}"] details`);if(details)details.open=true;}
 }
 async function edit(slug){editing=slug?await ctx.api('admin/auctions/'+encodeURIComponent(slug)):null;if(editing)U.sync(editing.server_now);
 saveSlug=editing?.session.slug||'selection-'+crypto.randomUUID();const form=$('#auction-form');form.reset();form.elements.title.value=editing?.session.title||'';const start=editing?.session.starts_at||new Date(Date.now()+3600000).toISOString(),end=editing?.session.ends_at||new Date(Date.now()+7200000).toISOString();form.elements.starts_at.value=localInput(start);form.elements.ends_at.value=localInput(end);$('#auction-editor-title').textContent=editing?'Edit this session':'Create a session';$('#auction-form-error').textContent='';$('#auction-timezone').textContent='Times are entered in '+Intl.DateTimeFormat().resolvedOptions().timeZone+'. Each bidder sees their own local time.';
 $('#auction-car-options').innerHTML=bidCars.filter(v=>v.status==='available'&&(!v.locked||editing?.lots.some(l=>l.vehicle_id===v.id))).map(v=>{const lot=editing?.lots.find(l=>l.vehicle_id===v.id);return `<div class="auction-car-option"><label class="auction-car-choice"><input type="checkbox" name="car" value="${v.id}" ${lot?'checked':''}><img src="${U.asset(v.image)}" alt=""><span><strong>${U.escape(v.brand+' '+v.model)}</strong><small>${U.escape(v.ref)} · ${v.year}</small></span></label><label>Opening USD<input type="number" min="1" max="10000000" step="1" data-opening="${v.id}" value="${lot?.opening_amount||v.price||1000}"></label><label>Increase USD<input type="number" min="1" max="100000" step="1" data-increment="${v.id}" value="${lot?.increment||100}"></label></div>`;}).join('')||'<p>Upload cars in Bidding cars first. Public sale inventory is never selected here.</p>';
 $('#auction-member-options').innerHTML=bidders.filter(b=>b.enabled).map(b=>`<label class="auction-member-choice"><input type="checkbox" name="member" value="${b.id}" ${editing?.members.includes(b.id)?'checked':''}><span><strong>${U.escape(b.name)}</strong><small>${U.escape(b.email)}${b.activation_pending?' · Setup pending':''}</small></span></label>`).join('')||'<p>Invite members before creating a session.</p>';
 $('#auction-editor').showModal();
 }
 async function save(status){const form=$('#auction-form');if(!form.reportValidity())return;const cars=[...form.querySelectorAll('input[name=car]:checked')],members=[...form.querySelectorAll('input[name=member]:checked')].map(input=>input.value);if(!cars.length||!members.length){$('#auction-form-error').textContent='Select at least one car and one invited member.';return;}
 const start=new Date(form.elements.starts_at.value),end=new Date(form.elements.ends_at.value);if(start.getTime()<U.now()||end-start<=300000||end-start>604800000){$('#auction-form-error').textContent='Choose a future start and a closing time more than 5 minutes and no more than 7 days later.';return;}
 const body={id:editing?.session.id||null,version:editing?.session.version||1,title:form.elements.title.value,slug:saveSlug,starts_at:start.toISOString(),ends_at:end.toISOString(),status,lots:cars.map(input=>({vehicle_id:input.value,opening_amount:Number(form.querySelector(`[data-opening="${input.value}"]`).value),increment:Number(form.querySelector(`[data-increment="${input.value}"]`).value)})),members};
 await ctx.operate(async()=>{await ctx.api('admin/auctions',body,'POST');$('#auction-editor').close();room=null;$('#auction-monitor').hidden=true;await refresh();ctx.showToast(status==='draft'?'Session saved privately.':'Session scheduled. Bidding opens automatically at the chosen time.');},'Saving your bidding session…');
 }
 function init(context){ctx=context;
 document.addEventListener('jht:admin-view',async event=>{active=event.detail;clearTimeout(poll);if(!['auctions','bidders','bidcars'].includes(active))return;$('#auction-session-list').innerHTML='<div class="auction-empty auction-loading"><span class="auction-spinner" aria-hidden="true"></span><p>Loading your private sessions…</p></div>';if(active==='bidders')$('#bidder-list').innerHTML='<div class="auction-empty auction-loading"><span class="auction-spinner" aria-hidden="true"></span><p>Loading your invited members…</p></div>';await refresh();schedule();});
 function schedule(){clearTimeout(poll);poll=setTimeout(async()=>{if(!document.hidden&&!$('dialog[open]')&&['auctions','bidders','bidcars'].includes(active))await refresh();if(['auctions','bidders','bidcars'].includes(active))schedule();},room&&U.phase(room.session)==='live'?5000:15000);}
 $('#new-bid-car').addEventListener('click',()=>ctx.openBidCar());
 $('#new-auction').addEventListener('click',()=>edit().catch(error=>ctx.showToast(error.message,'error')));
 $('#auction-form').addEventListener('submit',event=>{event.preventDefault();save('scheduled');});$('#auction-save-draft').addEventListener('click',()=>save('draft'));
 $('[data-close-auction]').addEventListener('click',()=>$('#auction-editor').close());$('[data-close-bidder]').addEventListener('click',()=>$('#bidder-editor').close());
 $('#invite-bidder').addEventListener('click',()=>{$('#bidder-form').reset();$('#bidder-editor').showModal();});
 $('#bidder-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);ctx.operate(async()=>{await ctx.api('admin/bidders',{name:data.get('name'),email:data.get('email')},'POST');$('#bidder-editor').close();await refresh();ctx.showToast('Private invitation sent. The member chooses their own password.');},'Sending the invitation…');});
 for(const dialog of [$('#auction-editor'),$('#bidder-editor')])dialog.addEventListener('cancel',event=>{if(document.body.classList.contains('is-saving'))event.preventDefault();});
 document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;
 if(button.dataset.editBidCar)ctx.openBidCar(bidCars.find(v=>v.id===button.dataset.editBidCar));
 if(button.dataset.archiveBidCar)ctx.operate(async()=>{const v=bidCars.find(v=>v.id===button.dataset.archiveBidCar);await ctx.api('admin/bid-vehicles/'+v.id,ctx.writable({...v,status:'archived'}),'PUT');await refresh();ctx.showToast('Bidding car archived. Its history is retained.');},'Archiving bidding car…');
 if(button.id==='retry-auctions')refresh();
 if(button.dataset.monitor)monitor(button.dataset.monitor).catch(error=>ctx.showToast(error.message,'error'));
 if(button.dataset.editSession)edit(button.dataset.editSession).catch(error=>ctx.showToast(error.message,'error'));
 if(button.dataset.copySession){navigator.clipboard.writeText(location.origin+'/bidding/?session='+encodeURIComponent(button.dataset.copySession)).then(()=>ctx.showToast('Private session link copied. Only assigned members can enter.')).catch(()=>ctx.showToast('Open the session monitor to use the private sign-in link.'));}
 if(button.dataset.cancelSession&&confirm('Cancel this session? All cars stop accepting bids. The bidding history stays saved.')){const s=sessions.find(s=>s.id===button.dataset.cancelSession);ctx.operate(async()=>{await ctx.api('admin/auctions/'+s.id+'/cancel',{version:s.version},'POST');await refresh();ctx.showToast('Session cancelled. Its history is preserved.');},'Cancelling session…');}
 if(button.dataset.confirmLot&&confirm('Confirm this winning bid and reserve the vehicle? Payment and export remain with your team.'))ctx.operate(async()=>{await ctx.api('admin/auctions/'+button.dataset.confirmLot+'/confirm',{version:1},'POST');await ctx.reloadInventory();await refresh();ctx.showToast('Winner confirmed. The bidding car is now reserved.');},'Confirming the winner…');
 if(button.dataset.retryMember){const b=bidders.find(b=>b.id===button.dataset.retryMember);ctx.operate(async()=>{await ctx.api('admin/bidders',{name:b.name,email:b.email},'POST');await refresh();ctx.showToast('Invitation sent. The member can complete their account setup.');},'Retrying invitation…');}
 if(button.dataset.toggleMember)ctx.operate(async()=>{await ctx.api('admin/bidders/'+button.dataset.toggleMember,{enabled:button.dataset.enabled==='true'},'PUT');await refresh();ctx.showToast('Member access updated. Disabled accounts cannot bid.');},'Updating member access…');
 });
 }
 window.JHTAuctionsAdmin={init,refresh,vehicles:()=>bidCars};
})();
