(() => {
 'use strict';
 const U=window.JHTAuction,$=s=>document.querySelector(s);
 let room=null,member=null,sessionSlug=new URLSearchParams(location.search).get('session')||'',poll,liveConnection=null,lastLobby='',polling=false,lastFresh=0,candidate=null,submitting=false,lastPhase='',invitation=null;
 const requests=new Map(),photos=new Map();
 const fragment=new URLSearchParams(location.hash.slice(1));
 if(fragment.has('access_token')){invitation={accessToken:fragment.get('access_token'),refreshToken:fragment.get('refresh_token')||''};history.replaceState(null,'',location.pathname+location.search);}
 const fontReady=document.fonts?Promise.allSettled([document.fonts.load('900 36px BidDisplay'),document.fonts.load('400 14px BidSans')]):Promise.resolve();fontReady.then(()=>document.body.classList.add('bid-fonts-ready'));
 function show(selector){for(const section of ['#bid-loading','#bid-access','#bid-lobby','#bid-room','#bid-unavailable'])$(section).hidden=section!==selector;window.JHTUI?.headline($(selector).querySelector('h1'),{compact:true});}
 function notify(text){$('#bid-toast').textContent=text;$('#bid-toast').classList.add('is-visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#bid-toast').classList.remove('is-visible'),5000);}
 async function api(path,body){let response;try{response=await fetch('/api/bidder/'+path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});}catch{throw Error('The connection was interrupted. Please retry; a repeated bid will not be counted twice.');}
 let data;try{data=await response.json();}catch{throw Error('The server could not confirm this request. Please try again.');}
 if(!response.ok){const error=Error(data.error||'This request could not be completed.');error.status=response.status;throw error;}return data;}
 function setMember(data){member=data;$('#member-name').textContent=data.name;$('#bid-signout').hidden=false;}
 function bidAsset(value){return U.asset(value).replace(/^\/api\/media\//,'/api/bidder/media/');}
 async function openLobby(){show('#bid-loading');clearTimeout(poll);liveConnection?.close();room=null;sessionSlug='';history.replaceState(null,'',location.pathname);const data=await api('sessions');renderLobby(data);show('#bid-lobby');liveConnection=window.JHTLive.connect('/api/bidder/lobby/stream',{onData:renderLobby,onDenied:()=>showLogin('Sign in again to view your invitations.')});}
 function renderLobby(data){U.sync(data.server_now);const markup=data.sessions.length?data.sessions.map(s=>`<article class="auction-session-card"><div><span class="auction-badge ${U.phase(s)}">${U.escape(U.phase(s))}</span><h2>${U.escape(s.title)}</h2><p>${U.date(s.starts_at)} — ${U.date(s.ends_at)}</p><small>${s.lot_count} selected cars</small></div><button class="secondary-action" data-open-session="${U.escape(s.slug)}">Enter session ↗</button></article>`).join(''):'<div class="auction-empty"><h2>Your invitation is ready.</h2><p>JHT Korea will assign your account to a session. You will find its date, countdown and cars here.</p></div>';if(markup!==lastLobby){$('#bid-session-list').innerHTML=markup;lastLobby=markup;}}
 async function openRoom(slug){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)||slug.length>100){show('#bid-unavailable');return;}
 clearTimeout(poll);liveConnection?.close();sessionSlug=slug;history.replaceState(null,'',location.pathname+'?session='+encodeURIComponent(slug));show('#bid-loading');try{room=await api('sessions/'+slug);U.sync(room.server_now);lastFresh=performance.now();room.session.ends_at=new Date(Math.max(Date.parse(room.session.ends_at),...room.lots.map(l=>Date.parse(l.closes_at)))).toISOString();renderRoom();show('#bid-room');tick();$('#bid-connection').textContent='Latest bids verified.';schedulePoll();}catch(error){if([401,403].includes(error.status)){showLogin(error.message);return;}show('#bid-unavailable');$('#bid-unavailable-copy').textContent=error.message;}}
 function renderRoom(){const s=room.session;$('#bid-session-title').textContent=s.title;$('#bid-session-date').textContent=U.date(s.starts_at)+' · '+Intl.DateTimeFormat().resolvedOptions().timeZone;$('#bid-lots').replaceChildren();for(const l of room.lots){const article=document.createElement('article');article.className='bid-lot';article.dataset.lot=l.id;article.innerHTML=`<div class="bid-lot-photo"><img alt="${U.escape(l.vehicle.brand+' '+l.vehicle.model)}" src="${bidAsset(l.vehicle.image)}"><div class="bid-photo-nav"><button type="button" data-photo-step="-1" aria-label="Previous vehicle photo">←</button><span data-photo-count></span><button type="button" data-photo-step="1" aria-label="Next vehicle photo">→</button></div></div><div class="bid-lot-copy"><span class="auction-eyebrow">${U.escape(l.vehicle.ref||'PRIVATE SELECTION')}</span><h2>${U.escape(l.vehicle.brand+' '+l.vehicle.model)}</h2><p class="bid-specs">${U.escape([l.vehicle.year,l.vehicle.body,l.vehicle.fuel,l.vehicle.transmission].filter(Boolean).join(' · '))}</p><div class="bid-lot-price"><div><small data-price-label></small><strong data-price></strong></div><div><small data-lot-time-label></small><span data-lot-countdown aria-live="off"></span></div></div><p class="bid-lot-state" data-lot-state></p><form class="bid-lot-form" data-bid-form="${l.id}"><label>Your bid · USD<input type="number" name="amount" step="1" max="10000000" required inputmode="numeric" aria-label="Your bid for ${U.escape(l.vehicle.brand+' '+l.vehicle.model)}"></label><button type="submit" class="primary-action">Review bid ↗</button></form><small class="bid-specs" data-increment></small><details><summary>Recent bids</summary><ol class="auction-history" data-bid-history></ol></details></div>`;$('#bid-lots').append(article);photos.set(l.id,0);setPhoto(l.id,0);}
 updateRoom();}
 function updateRoom(){if(!room)return;$('#bid-session-date').textContent=U.date(room.session.starts_at)+' · '+Intl.DateTimeFormat().resolvedOptions().timeZone;const notice=$('#bid-opening-notice');notice.textContent=room.session.start_notice||'';notice.hidden=!notice.textContent||U.now()>=Date.parse(room.session.starts_at);for(const l of room.lots){const article=$(`[data-lot="${l.id}"]`);if(!article)continue;article.querySelector('[data-price]').textContent=U.money(l.highest_amount||l.opening_amount);article.querySelector('[data-price-label]').textContent=l.highest_amount?'HIGHEST BID':'OPENING PRICE';article.querySelector('[data-increment]').textContent='Minimum increase '+U.money(l.increment)+' · '+l.bid_count+(l.bid_count===1?' bid':' bids');const input=article.querySelector('input');input.min=l.next_bid;input.placeholder=String(l.next_bid);if(l.leading)input.value=l.highest_amount;else if(!input.value)input.value=l.next_bid;article.querySelector('[data-bid-history]').innerHTML=l.history.map(h=>`<li><span>${h.mine?'Your bid':'Member bid'}<small>${U.date(h.created_at)}</small></span><strong>${U.money(h.amount)}</strong></li>`).join('')||'<li>No bids yet.</li>';}
 tick();}
 function tick(){if(!room||$('#bid-room').hidden)return;const s=room.session,phase=U.phase(s),future=phase==='scheduled';$('#bid-session-phase').textContent=phase==='live'?'BIDDING IS LIVE':phase==='ended'?'BIDDING COMPLETE':phase==='cancelled'?'SESSION CANCELLED':'PRIVATE BIDDING · UPCOMING';$('#bid-countdown-label').textContent=future?'OPENS IN':phase==='live'?'SESSION CLOSES IN':'SESSION STATUS';$('#bid-session-countdown').textContent=future?U.countdown(s.starts_at):phase==='live'?U.countdown(s.ends_at):phase==='cancelled'?'Cancelled':'Closed';const stale=performance.now()-lastFresh>15000;
 for(const l of room.lots){const article=$(`[data-lot="${l.id}"]`);if(!article)continue;const closed=U.now()>=Date.parse(l.closes_at),live=phase==='live'&&!closed;let text=phase==='cancelled'?'This session was cancelled. No winning bid is confirmed.':future?'Bidding opens at '+U.date(s.starts_at)+'.':closed?(l.highest_amount?(l.leading?(l.confirmed?'Your winning bid is confirmed. JHT will contact you.':'You hold the winning bid. Awaiting JHT confirmation.'):'Bidding has closed. Thank you for taking part.'):'Closed without bids.'):(l.leading?'You have the highest bid.':l.my_bid?'You have been outbid. Review the latest price before bidding again.':'Your place is ready. Review an amount to place your first bid.');
 if(l.closed_early&&closed)text='Closed early by JHT Korea. '+text;const state=article.querySelector('[data-lot-state]');state.textContent=text;state.classList.toggle('is-leading',!!l.leading);article.querySelector('[data-lot-time-label]').textContent=future?'OPENS IN':'CAR CLOSES IN';article.querySelector('[data-lot-countdown]').textContent=phase==='cancelled'?'Cancelled':future?U.countdown(s.starts_at):closed?'Closed':U.countdown(l.closes_at);const form=article.querySelector('form');form.querySelector('button').disabled=!live||!!l.leading||stale;form.querySelector('input').disabled=!live||!!l.leading||stale;}
 if(candidate&&$('#bid-confirm').open){const lot=room.lots.find(l=>l.id===candidate.lot),closed=!lot||U.now()>=Date.parse(lot.closes_at)||phase!=='live';$('#submit-confirmed-bid').disabled=submitting||stale||closed;if(closed&&!submitting)$('#bid-confirm-error').textContent='Bidding is closed for this car. Your draft bid was not submitted.';}if(lastPhase&&lastPhase!==phase){lastPhase=phase;refreshRoom();}else lastPhase=phase;}
 function acceptRoom(data){if(!room)return;const before=new Map(room.lots.map(l=>[l.id,l])),ids=room.lots.map(l=>l.id).join(',');room=data;U.sync(data.server_now);lastFresh=performance.now();if(ids!==data.lots.map(l=>l.id).join(','))renderRoom();else updateRoom();$('#bid-connection').textContent='Live bids verified at '+new Intl.DateTimeFormat(undefined,{timeStyle:'medium'}).format(new Date());$('#bid-connection').classList.remove('is-stale');for(const l of room.lots){if(before.get(l.id)?.leading&&!l.leading)notify('You have been outbid on '+l.vehicle.brand+' '+l.vehicle.model+'.');if(l.closed_early&&!before.get(l.id)?.closed_early)notify('Bidding closed early for '+l.vehicle.brand+' '+l.vehicle.model+'. The highest bid is retained for JHT confirmation.');}const notice=$('#bid-opening-notice');notice.textContent=room.session.start_notice||'';notice.hidden=!notice.textContent||U.now()>=Date.parse(room.session.starts_at);}
 async function refreshRoom(){if(polling||!room||document.hidden)return;polling=true;try{const data=await api('sessions/'+sessionSlug);acceptRoom(data);}catch(error){lastFresh=-Infinity;tick();$('#bid-connection').textContent=error.message+' Bidding is paused here until the latest prices are verified.';$('#bid-connection').classList.add('is-stale');if([401,403].includes(error.status))showLogin('Your session has ended. Sign in again to continue.');}finally{polling=false;}}
 function schedulePoll(){liveConnection?.close();if(!room)return;liveConnection=window.JHTLive.connect('/api/bidder/sessions/'+encodeURIComponent(sessionSlug)+'/stream',{onData:acceptRoom,onState:state=>{if(state==='interrupted'){lastFresh=-Infinity;tick();$('#bid-connection').textContent='Reconnecting. Bids are paused here until the latest price is verified.';$('#bid-connection').classList.add('is-stale');}},onDenied:()=>showLogin('Your invitation or session has ended. Sign in again to continue.')});}
 function setPhoto(id,step){const l=room.lots.find(l=>l.id===id),gallery=l.vehicle.gallery?.length?l.vehicle.gallery:[l.vehicle.image],index=((photos.get(id)||0)+step+gallery.length)%gallery.length;photos.set(id,index);const article=$(`[data-lot="${id}"]`);window.JHTUI.photo(article.querySelector('.bid-lot-photo>img'),bidAsset(gallery[index]));article.querySelector('[data-photo-count]').textContent=`${index+1} / ${gallery.length}`;article.querySelector('.bid-photo-nav').hidden=gallery.length<2;}
 function showLogin(error=''){clearTimeout(poll);liveConnection?.close();liveConnection=null;if($('#bid-confirm').open)window.JHTUI.closeDialog($('#bid-confirm'));requests.clear();$('#bid-login-form').hidden=false;$('#bid-setup-form').hidden=true;$('#bid-access-title').textContent='A private collection.';$('#bid-access-copy').textContent='Sign in with the account invited by JHT Korea.';member=null;room=null;$('#member-name').textContent='';$('#bid-signout').hidden=true;show('#bid-access');$('#bid-access-error').textContent=error;}
 $('#bid-login-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;button.textContent='Verifying your invitation…';try{const data=new FormData(form),result=await api('auth/login',{email:data.get('email'),password:data.get('password')});form.elements.password.value='';setMember(result);await(sessionSlug?openRoom(sessionSlug):openLobby());}catch(error){$('#bid-access-error').textContent=error.message;}finally{button.disabled=false;button.textContent='Enter the collection ↗';}});
 $('#bid-setup-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;try{const result=await api('auth/activate',{...invitation,password:new FormData(form).get('password')});invitation=null;form.elements.password.value='';setMember(result);await openLobby();}catch(error){$('#bid-access-error').textContent=error.message;}finally{button.disabled=false;}});
 $('#bid-signout').addEventListener('click',async()=>{const button=$('#bid-signout');button.disabled=true;try{await api('auth/logout',{});showLogin();}catch(error){notify(error.message);}finally{button.disabled=false;}});
 $('#back-to-sessions').addEventListener('click',()=>openLobby().catch(error=>notify(error.message)));$('#bid-retry').addEventListener('click',()=>openLobby().catch(error=>showLogin(error.message)));
 $('#bid-session-list').addEventListener('click',event=>{const button=event.target.closest('[data-open-session]');if(button)openRoom(button.dataset.openSession);});
 $('#bid-lots').addEventListener('click',event=>{const button=event.target.closest('[data-photo-step]');if(button)setPhoto(button.closest('[data-lot]').dataset.lot,Number(button.dataset.photoStep));});
 $('#bid-lots').addEventListener('submit',event=>{event.preventDefault();const form=event.target,l=room.lots.find(l=>l.id===form.dataset.bidForm),amount=Number(form.elements.amount.value);if(!form.reportValidity()||!Number.isSafeInteger(amount)||amount<l.next_bid||U.phase(room.session)!=='live'||l.leading||performance.now()-lastFresh>15000){notify('Refresh the latest price before placing a bid.');return;}
 const previous=requests.get(l.id);candidate={lot:l.id,amount,request_id:previous?.amount===amount?previous.request_id:crypto.randomUUID()};requests.set(l.id,candidate);$('#bid-confirm-form').reset();$('#bid-confirm-title').textContent=U.money(amount);$('#confirm-car-name').textContent=l.vehicle.brand+' '+l.vehicle.model;$('#bid-confirm-error').textContent='';$('#bid-confirm').showModal();});
 $('#close-bid-confirm').addEventListener('click',()=>{if(!submitting)window.JHTUI.closeDialog($('#bid-confirm'));});$('#bid-confirm').addEventListener('cancel',event=>{if(submitting)event.preventDefault();});
 $('#bid-confirm-form').addEventListener('submit',async event=>{event.preventDefault();if(submitting||!candidate||!event.currentTarget.reportValidity())return;submitting=true;$('#bid-confirm-form').setAttribute('aria-busy','true');$('#submit-confirmed-bid').disabled=true;$('#close-bid-confirm').disabled=true;$('#bid-accept').disabled=true;$('#bid-submit-status').hidden=false;$('#bid-confirm-error').textContent='';try{await api('lots/'+candidate.lot+'/bids',{amount:candidate.amount,request_id:candidate.request_id});requests.delete(candidate.lot);window.JHTUI.closeDialog($('#bid-confirm'));notify('Your bid was accepted.');await refreshRoom();}catch(error){$('#bid-confirm-error').textContent=error.message;if(error.status&&error.status<500)requests.delete(candidate.lot);await refreshRoom();}finally{submitting=false;$('#bid-confirm-form').removeAttribute('aria-busy');$('#submit-confirmed-bid').disabled=false;$('#close-bid-confirm').disabled=false;$('#bid-accept').disabled=false;$('#bid-submit-status').hidden=true;}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&room)refreshRoom();});setInterval(tick,1000);
 async function boot(){await fontReady;if(invitation){$('#bid-login-form').hidden=true;$('#bid-setup-form').hidden=false;$('#bid-access-title').textContent='Your invitation. Your access.';$('#bid-access-copy').textContent='Choose a password to activate your private bidding account.';show('#bid-access');return;}try{setMember(await api('auth/session'));await(sessionSlug?openRoom(sessionSlug):openLobby());}catch(error){showLogin(error.status===401?'':error.message);}}
 boot();
})();
